# Site settings
title: 'Ethernet e-Research Hackfest'
description: 'The Sci-GaIA e-Research Hackfest in Addis Ababa'
url: 'http://localhost:4000/'

# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

intro: 'The Hackfest brings together e-Science platform developers and scientists, to build tools for scientific discovery. Bring your science to the web and the web to your science. These pages contain everything you need to get going and get it built'

organiser:
  name: 'EthERNet'
  email: info@sci-gaia.eu
  twitter_username: ei4africa
  twitter_hashtags:
  facebook_username:
  github_username: Sci-GaIA
  linkedin_username:
# Made with love using these tools. This goes in the footer. Uses Devicons
built_with:
  - jekyll_small
  - bootstrap
  - atom
  - github_full
  - travis

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
